config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session
  resources :passwords, param: :token
  get "welcome/index"
  get "welcome/chat"
  post "welcome/chat"
  post "welcome/reset_chat"
  root action: :index, controller: "welcome"
  
  namespace :rui do
    get "about", to: "pages#about"
    get "pricing", to: "pages#pricing"
    get "dashboard", to: "pages#dashboard"
    get "projects", to: "pages#projects"
    get "project", to: "pages#project"
    get "messages", to: "pages#messages"
    get "message", to: "pages#message"
    get "assignments", to: "pages#assignments"
    get "calendar", to: "pages#calendar"
    get "people", to: "pages#people"
    get "profile", to: "pages#profile"
    get "activity", to: "pages#activity"
    get "settings", to: "pages#settings"
    get "notifications", to: "pages#notifications"
    get "billing", to: "pages#billing"
    get "team", to: "pages#team"
    get "integrations", to: "pages#integrations"
  end

  if Rails.env.development?
     # Visit the start page for Rails UI any time at /railsui/start
    mount Railsui::Engine, at: "/railsui"
  end

  # Inherits from Railsui::PageController#index
  # To override, add your own page#index view or change to a new root
  #root action: :index, controller: "railsui/default"




  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end


    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id])
    end


    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end


    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/rui/pages_controller.rb
class Rui::PagesController < ApplicationController
  Railsui.config.pages.each do |page|
    define_method(page.to_sym) do
      layout = Railsui::Pages.installed_pages[page.to_s]['namespace'] == 'admin' && lookup_context.exists?("layouts/rui/railsui_admin") ? "rui/railsui_admin" : "rui/railsui"
      render "rui/pages/#{page}", layout: layout
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      session = @user.sessions.create!
      cookies.signed.permanent[:session_token] = { value: session.id, httponly: true }
      
      redirect_to root_path, notice: "Welcome! You have signed up successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def user_params
      params.require(:user).permit(:email_address, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  allow_unauthenticated_access only: [:index]
  def index
  end

  
  

  def reset_chat
    session[:messages] = []
    redirect_to welcome_chat_path
  end  
  def chat
    @message = params[:message]
    @messages = session[:messages] ||= []  #session[:messages] = []

    if request.post? && @message.present?
      msg = {:user => "#{@message}"}
      @messages << "[👤]: #{@message}"

      #Agent
      ai = RotiAgent.new
      @messages.each {|message| ai.transcript << {:user => "#{message}"}  }
      
      response = ai.chat_completion(openai: "gpt-4o-mini", loop: true)
      @messages <<  "[🤖]: #{response}"
      session[:messages] = @messages
      
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.append(
            "chat-messages",
            partial: "messages",
            locals: { messages: [session[:messages][-2],session[:messages][-1] ] } #last two messages
          )
        end
        format.html
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def spacer(amount = 16)
    render "rui/shared/email_spacer", amount: amount
  end

  def email_action(action, url, options={})
    align = options[:align] ||= "left"
    theme = options[:theme] ||= "primary"
    fullwidth = options[:fullwidth] ||= false
    render "rui/shared/email_action", align: align, theme: theme, action: action, url: url, fullwidth: fullwidth
  end

  def email_callout(&block)
    render "rui/shared/email_callout", block: block
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/rui/railsui.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>
      <%= Railsui.config.application_name || "Rails UI" %>
    </title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>

    <%= railsui_head %>
  </head>

  <body class="<%= railsui_body_classes %>">
    <%= render "rui/shared/flash" %>
    <% if content_for(:header).present? %>
      <%= yield :header %>
    <% else %>
      <%= render "rui/shared/nav" %>
    <% end %>
    <%= yield %>
    <%= railsui_launcher if Rails.env.development? %>
  </body>
</html>

app/views/rui/shared/_email_callout.html.erb
<table class="callout">
  <tbody>
    <td>
      <%= capture(&block) %>
    </td>
  </tbody>
</table>

app/views/rui/shared/_footer.html.erb
<footer class="container mx-auto px-4 pb-4">
  <nav role="Utility navigation">
    <ul class="lg:flex items-center justify-center text-center lg:my-6 mb-6 lg:text-base text-lg">
      <li class="py-3 lg:py-0">
        <%= link_to "Product", "#", class: "px-3 py-2 hover:text-primary-700 dark:hover:text-primary-500" %>
      </li>
      <li class="py-3 lg:py-0">
        <%= link_to "Customers", "#", class: "px-3 py-2 hover:text-primary-700 dark:hover:text-primary-500" %>
      </li>
      <li class="py-3 lg:py-0">
        <%= link_to "Features", "#", class: "px-3 py-2 hover:text-primary-700 dark:hover:text-primary-500" %>
      </li>
      <% if defined?(rui_pricing_path) %>
        <li class="py-3 lg:py-0">
          <%= link_to "Pricing", rui_pricing_path, class: "px-3 py-2 hover:text-primary-700 dark:hover:text-primary-500" %>
        </li>
      <% end %>
      <% if defined?(rui_about_path)%>
        <li class="py-3 lg:py-0">
          <%= link_to "Company", rui_about_path, class: "px-3 py-2 hover:text-primary-700  dark:hover:text-primary-500" %>
        </li>
      <% end %>
    </ul>
  </nav>

  <ul class="flex items-center justify-center gap-6 mb-6">
    <li>
      <%= link_to "#", class: "group", target: :_blank do %>
        <%= icon "facebook", custom_path: "/railsui/social/facebook.svg", class: "size-6 fill-current text-slate-400 group-hover:text-primary-600 dark:group-hover:text-primary-500" %>
      <% end %>
    </li>
    <li>
      <%= link_to "#", class: "group", target: :_blank do %>
        <%= icon "x", custom_path: "/railsui/social/x.svg", class: "size-6 fill-current text-slate-400 group-hover:text-primary-600 dark:group-hover:text-primary-500" %>
      <% end %>
    </li>
    <li>
      <%= link_to "#", class: "group", target: :_blank do %>
        <%= icon "linkedin", custom_path: "/railsui/social/linkedin.svg", class: "size-6 fill-current text-slate-400 group-hover:text-primary-600 dark:group-hover:text-primary-500" %>
      <% end %>
    </li>
    <li>
      <%= link_to "#", class: "group", target: :_blank do %>
        <%= icon "youtube", custom_path: "/railsui/social/youtube.svg", class: "size-6 fill-current text-slate-400 group-hover:text-primary-600 dark:group-hover:text-primary-500" %>
      <% end %>
    </li>
  </ul>

  <p class="text-center text-slate-600 text-sm">&copy; <%= Railsui.config.application_name %> All Rights Reserved. Made with <a
      href="https://railsui.com" class="underline" target="_blank">Rails UI</a></p>
</footer>

app/views/rui/shared/admin/_nav.html.erb
<header class="px-4 dark:border-b dark:border-slate-700 bg-slate-800 <%= local_assigns[:header_title].present? ? 'sm:py-6 py-4' : 'sm:pt-6 pt-4' %>" data-controller="nav">
  <div class="lg:flex flex-wrap items-center justify-start container mx-auto border-b border-slate-700 pb-4">
    <div class="flex items-center justify-between">

      <%= link_to root_path do %>
        <svg class="fill-current text-primary-500 sm:w-10 w-6" width="32" height="42" viewBox="0 0 32 42" fill="none"
          xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" clip-rule="evenodd"
            d="M7.17241 0C3.2112 0 0 3.2112 0 7.17241V22.0065C0 25.9678 3.2112 29.1789 7.17241 29.1789C11.1336 29.1789 14.3448 25.9678 14.3448 22.0065V7.17241C14.3448 3.2112 11.1336 0 7.17241 0ZM24.8276 0C20.8664 0 17.6552 3.2112 17.6552 7.17241V34.8276C17.6552 38.7888 20.8664 42 24.8276 42C28.7888 42 32 38.7888 32 34.8276V7.17241C32 3.2112 28.7888 0 24.8276 0Z" />
        </svg>
      <% end %>

      <button id="admin-nav-toggle" data-action="click->nav#toggle"
        class="lg:hidden block px-1 py-px rounded focus:ring-2 focus:ring-slate-100/30 focus:bg-slate-700 focus:shadow-sm active:bg-slate-700 group dark:focus:bg-slate-800 dark:focus:ring-slate-600 dark:focus:shadow-sm"
        role="Mobile navigation toggle">
        <div role="none" data-nav-target="menuBars">
          <%= icon "bars-3-bottom-left", class:  "stroke-current w-9 h-9 text-slate-300 group-focus:text-primary-200 dark:text-slate-400 dark:group-focus:text-slate-100" %>
        </div>
        <div role="none" data-nav-target="menuCross" class="hidden">
          <%= icon "x-mark", class:  "stroke-current w-9 h-9 text-slate-300 group-focus:text-primary-200 dark:text-slate-400 dark:group-focus:text-slate-100" %>
        </div>
      </button>
    </div>
    <div class="text-white lg:pl-6 flex-1 lg:py-0 py-4 lg:flex" data-nav-target="nav"
      data-transition-enter-active="transition ease-out duration-200" data-transition-enter-from="opacity-0 scale-95"
      data-transition-enter-to="opacity-100 scale-100" data-transition-leave-from="opacity-100 scale-100"
      data-transition-leave-active="transition ease-in duration-200" data-transition-leave-to="opacity-0 scale-95">

      <nav class="flex-1">
        <ul class="lg:flex md:flex-nowrap flex-wrap items-center sm:mx-0 -mx-2 lg:space-x-px space-y-px lg:space-y-0">
          <%= render "rui/shared/admin/nav_links" %>
        </ul>
      </nav>

      <%# Notifications Dropdown %>
      <div class="sm:flex justify-end flex-1 md:mr-6 mr-3 md:mt-3 relative" data-controller="railsui-dropdown">

        <button type="button" class="flex group sm:justify-center items-center md:w-auto w-full px-2 py-3 md:p-0"
          data-action="click->railsui-dropdown#toggle click@window->railsui-dropdown#hide">
          <div class="relative">
            <%= icon "bell", class:  "text-slate-300 size-6 group-hover:text-slate-400 dark:group-hover:text-slate-300 stroke-current" %>
            <span
              class="w-[10px] h-[10px] bg-red-500 rounded-full hover:animate-pulse absolute top-0 right-0 z-20 dark:bg-primary-400"></span>
          </div>
          <span class="md:hidden text-slate-300 dark:text-slate-200 text-base ml-2">Notifications</span>
        </button>

        <div
          class="origin-to-right md:absolute mt-2 ml-2 md:ml-0 md:mt-0 md:shadow-xl sm:w-[320px] md:min-w-[320px]  divide-y text-left dark:divide-gray-600
          hidden transition transform origin-top-right absolute right-0 top-10 bg-white rounded-lg shadow-xl shadow-slate-900/10 border border-slate-200 md:w-[320px] w-full z-50 py-2 dark:bg-slate-700 dark:shadow-slate-900/50 dark:border-slate-500/60 md:text-sm text-base font-medium text-slate-600 dark:text-slate-200"
          data-railsui-dropdown-target="menu" data-transition-enter-from="opacity-0 scale-95"
          data-transition-enter-to="opacity-100 scale-100" data-transition-leave-from="opacity-100 scale-100"
          data-transition-leave-to="opacity-0 scale-95">
          <div class="px-4 py-3 md:py-2 flex items-center justify-between group">
            <div class="flex-1">
              <div class="flex items-start space-x-2">
                <%= image_tag demo_avatar_url(id: "10"), class: "size-6 object-cover rounded-full flex-shrink-0 mt-1", alt: "John D." %>
                <div class="flex-1">
                  <p class="truncate">John D. replied to <%= link_to "your comment", "#", class: "underline text-primary-600 hover:text-primary-700 dark:text-primary-400 dark:hover:text-primary-400" %></p>
                  <p class="text-xs text-slate-500 dark:text-slate-400">Just now</p>
                </div>
              </div>
            </div>

            <button
              class="opacity-0 group-hover:opacity-100 transition ease-in-out duration-300 flex items-center justify-center rounded-full w-7 h-7 hover:bg-slate-50/50 group border border-slate-200 hover:border-slate-300 focus:ring-4 focus:ring-slate-100/75 bg-white/50 dark:bg-slate-500/75 dark:focus:ring-slate-100/10 dark:border-slate-400 dark:hover:bg-white/20">
              <%= icon "x-mark", class:  "w-3 h-3 text-slate-600 group-hover:text-primary-600 dark:group-hover:text-slate-100 dark:text-slate-50 stroke-current" %>
            </button>
          </div>
          <div class="px-4 py-3 md:py-2 flex items-center justify-between group">
            <div class="flex-1">
              <div class="flex items-start space-x-2">
                <%= image_tag demo_avatar_url(id: "14", variant: "women"), class: "size-6 object-cover rounded-full flex-shrink-0 mt-1" %>
                <div class="flex-1">
                  <p>Jane D. posted  <%= link_to "an update", "#", class: "underline text-primary-600 hover:text-primary-700 dark:text-primary-400 dark:hover:text-primary-400" %></p>
                  <p class="text-xs text-slate-500 dark:text-slate-400">15 mins ago</p>
                </div>
              </div>
            </div>
            <button
              class="opacity-0 group-hover:opacity-100 transition ease-in-out duration-300 flex items-center justify-center rounded-full w-7 h-7 hover:bg-slate-50/50 group border border-slate-200 hover:border-slate-300 focus:ring-4 focus:ring-slate-100/75 bg-white/50 dark:bg-slate-500/75 dark:focus:ring-slate-100/10 dark:border-slate-400 dark:hover:bg-white/20">
              <%= icon "x-mark", class:  "w-3 h-3 text-slate-600 group-hover:text-primary-600 dark:group-hover:text-slate-100 dark:text-slate-50 stroke-current" %>
            </button>
          </div>
          <div class="px-4 py-3 md:py-2 flex items-center justify-between group">
            <div class="flex-1">
              <div class="flex items-start space-x-2">
                <%= image_tag demo_avatar_url(id: "24"), class: "size-6 object-cover rounded-full flex-shrink-0 mt-1" %>
                <div class="flex-1">
                  <p>Scotty P. shared <%= link_to "a repository", "#", class: "underline text-primary-600 hover:text-primary-700 dark:text-primary-400 dark:hover:text-primary-400" %></p>
                  <p class="text-xs text-slate-500 dark:text-slate-400">2 hours ago</p>
                </div>
              </div>
            </div>
            <button
              class="opacity-0 group-hover:opacity-100 transition ease-in-out duration-300 flex items-center justify-center rounded-full w-7 h-7 hover:bg-slate-50/50 group border border-slate-200 hover:border-slate-300 focus:ring-4 focus:ring-slate-100/75 bg-white/50 dark:bg-slate-500/75 dark:focus:ring-slate-100/10 dark:border-slate-400 dark:hover:bg-white/20">
              <%= icon "x-mark", class:  "w-3 h-3 text-slate-600 group-hover:text-primary-600 dark:group-hover:text-slate-100 dark:text-slate-50 stroke-current" %>
            </button>
          </div>
          <div>
            <%= link_to "#", class: "flex items-center justify-between group px-4 pt-3 pb-2 hover:bg-slate-50 hover:text-primary-500 text-sm group font-medium text-slate-500 dark:text-slate-200 dark:hover:bg-slate-700 dark:hover:text-white" do %>
              <span>View all notifications</span>
              <%= icon "chevron-right", class:  "group-hover:translate-x-1 transform transition ease-in-out size-4 text-slate-400 group-hover:text-primary-500 dark:group-hover:text-primary-200 stroke-current" %>
            <% end %>
          </div>
        </div>
      </div>
      <%# end Notifications Dropdown %>
      <div data-controller="railsui-dropdown" class="lg:flex relative lg:pt-0 pt-4">
        <button data-action="click->railsui-dropdown#toggle click@window->railsui-dropdown#hide"
          class="appearance-none rounded-full lg:w-10 w-12 lg:h-10 h-12 focus:ring-slate-200/90 hover:ring-slate-200/90 ring-2 ring-transparent box-content transition ease-in-out duration-200 flex-shrink-0 dark:focus:ring-primary-400 dark:hover:ring-slate-500">
          <%= image_tag demo_avatar_url, class: "lg:w-10 w-12 lg:h-10 h-12 rounded-full flex-shrink-0 select-none", alt: "John Smith" %>
        </button>
        <ul data-railsui-dropdown-target="menu"
          class="hidden transition transform origin-top-right absolute right-0 md:top-12 top-20 bg-white rounded-lg shadow-xl shadow-slate-900/10 border border-slate-200 md:w-[200px] w-full z-50 py-2 dark:bg-slate-700 dark:shadow-slate-900/50 dark:border-slate-500/60 md:text-sm text-base font-medium text-slate-600 dark:text-slate-200"
          data-transition-enter-active="transition ease-out duration-300"
          data-transition-enter-from="transform opacity-0 scale-95"
          data-transition-enter-to="transform opacity-100 scale-100"
          data-transition-leave-active="transition ease-in duration-300"
          data-transition-leave-from="transform opacity-100 scale-100"
          data-transition-leave-to="transform opacity-0 scale-95">

          <li>
            <%= link_to rui_settings_path, class: "py-2 px-4 hover:text-primary-600 focus:text-primary-600 flex items-center space-x-2 w-full group text-slate-600 dark:text-slate-300 dark:hover:text-primary-400" do %>
              <%= icon "cog-6-tooth", class: "flex-shrink-0 stroke-current size-5 text-slate-500 group-hover:text-primary-600 dark:group-hover:text-primary-400" %>
              <span>Settings</span>
            <% end %>
          </li>

          <li>
            <%= link_to rui_billing_path, class: "py-2 px-4 hover:text-primary-600 focus:text-primary-600 flex items-center space-x-2 w-full group text-slate-600 dark:text-slate-300 dark:hover:text-primary-400" do %>
              <%= icon "banknotes", class: "flex-shrink-0 stroke-current size-5 text-slate-500 group-hover:text-primary-600 dark:group-hover:text-primary-400" %>
              <span>Billing</span>
            <% end %>
          </li>

          <li>
            <%= button_to "#", method: :delete, class: "py-2 px-4 hover:text-primary-600 focus:text-primary-600 flex items-center space-x-2 w-full group text-slate-600 dark:text-slate-300 dark:hover:text-primary-400" do %>
              <%= icon "arrow-right-on-rectangle", class: "flex-shrink-0 stroke-current size-5 text-slate-500 group-hover:text-primary-600 dark:group-hover:text-primary-400" %>
              <span>Sign out</span>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="<%= local_assigns[:header_title].present? ? 'container mx-auto lg:pt-16 pt-6' : 'container mx-auto' %>">
    <div class="flex flex-wrap items-center justify-between relative">
      <% if local_assigns[:header_title].present? %>
        <h1 class="md:h2 h3 !text-white flex-1">
          <%= local_assigns[:header_title] %>
        </h1>
      <% end %>

      <%= yield %>
    </div>
  </div>
</header>

app/views/rui/shared/admin/_settings_nav.html.erb
<div class="bg-white border-b dark:bg-slate-800/50 dark:border-b dark:border-slate-700 px-4">
  <div class="container mx-auto sm:flex flex-wrap justify-between items-center">

    <nav role="navigation">
      <ul class="flex items-center justify-start sm:space-x-1 py-2 text-slate-600 sm:overflow-auto overflow-y-hidden scroll-smooth snap-start scrollbar-thin scrollbar-thumb-gray-200 scrollbar-track-gray-100/50 scrollbar-thumb-rounded">

        <li class="flex justify-center items-center sm:block">
          <%= nav_link_to "Account", rui_settings_path, active_class: "py-2 px-4 bg-slate-50 dark:bg-slate-900 rounded-lg transition ease-in-out duration-300 text-primary-600 dark:text-primary-400 font-medium flex items-center space-x-2 dark:hover:bg-slate-900/80", inactive_class: "py-2 px-4 rounded-lg transition ease-in-out duration-300 hover:bg-slate-50 hover:text-primary-600 dark:hover:text-primary-400 font-medium flex items-center space-x-2 group dark:text-slate-300 dark:hover:bg-slate-900" %>
        </li>

        <li class="flex justify-center items-center sm:block">
          <%= nav_link_to "Notifications", rui_notifications_path, active_class: "py-2 px-4 bg-slate-50 dark:bg-slate-900 rounded-lg transition ease-in-out duration-300 text-primary-600 dark:text-primary-400 font-medium flex items-center space-x-2 dark:hover:bg-slate-900/80", inactive_class: "py-2 px-4 rounded-lg transition ease-in-out duration-300 hover:bg-slate-50 hover:text-primary-600 dark:hover:text-primary-400 font-medium flex items-center space-x-2 group dark:text-slate-300 dark:hover:bg-slate-900" %>
        </li>

        <li class="flex justify-center items-center sm:block">
          <%= nav_link_to "Billing", rui_billing_path, active_class: "py-2 px-4 bg-slate-50 dark:bg-slate-900 rounded-lg transition ease-in-out duration-300 text-primary-600 dark:text-primary-400 font-medium flex items-center space-x-2 dark:hover:bg-slate-900/80", inactive_class: "py-2 px-4 rounded-lg transition ease-in-out duration-300 hover:bg-slate-50 hover:text-primary-600 dark:hover:text-primary-400 font-medium flex items-center space-x-2 group dark:text-slate-300 dark:hover:bg-slate-900" %>
        </li>

        <li class="flex justify-center items-center sm:block">
          <%= nav_link_to "Team", rui_team_path, active_class: "py-2 px-4 bg-slate-50 dark:bg-slate-900 rounded-lg transition ease-in-out duration-300 text-primary-600 dark:text-primary-400 font-medium flex items-center space-x-2 dark:hover:bg-slate-900/80", inactive_class: "py-2 px-4 rounded-lg transition ease-in-out duration-300 hover:bg-slate-50 hover:text-primary-600 dark:hover:text-primary-400 font-medium flex items-center space-x-2 group dark:text-slate-300 dark:hover:bg-slate-900" %>
        </li>

        <li class="flex justify-center items-center sm:block">
          <%= nav_link_to "Integrations", rui_integrations_path, active_class: "py-2 px-4 bg-slate-50 dark:bg-slate-900 rounded-lg transition ease-in-out duration-300 text-primary-600 dark:text-primary-400 font-medium flex items-center space-x-2 dark:hover:bg-slate-900/80", inactive_class: "py-2 px-4 rounded-lg transition ease-in-out duration-300 hover:bg-slate-50 hover:text-primary-600 dark:hover:text-primary-400 font-medium flex items-center space-x-2 group dark:text-slate-300 dark:hover:bg-slate-900" %>
        </li>
      </ul>
    </nav>
  </div>
</div>